apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: mongodb-namespace 
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: chi811008/my-app:1.4
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URL
          value: "mongodb://admin:password@mongodb-service.mongodb-namespace.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: mongodb-namespace
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001